# config.toml
[theme]
primaryColor = "#4CAF50"
backgroundColor = "#F5F5F5"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#000000"
font = "sans serif"

defaultLanguage = "en"

[server]
headless = true
port = $PORT